### ISSUE TITLE
Still WIP?

### ISSUE THREAD

**Issue by Sliim** [redguide/foreman#1]
Hi,
just a question, this cookbook is still in work in progress state?

**Comment by guilhem** [comment]
@Sliim this cookbook is not in a good shape, but #2 seems to be pretty cool.

If you want to contribute don't hesitate. And if you want to be a maintainer, just ask ;)

**Comment by Sliim** [comment]
Yeah, I'm working with @PierreRambaud and my question was related to his potential contribution :). I closed this issue because I think his PR is a better place to discuss about improvements of this cookbook (and it's not really an issue..) :)
