### ISSUE TITLE
RFE support foreman_chef plugin

### ISSUE THREAD

**Issue by ares** [redguide/foreman#4]
It would be super awesome if this could also install [Foreman chef](https://github.com/theforeman/foreman_chef) and [Smart proxy Chef](https://github.com/theforeman/smart_proxy_chef), also maybe a support for configuring [chef handlers on chef nodes](https://github.com/theforeman/chef-handler-foreman/).

It also makes me think about introducing kafo parser for chef cookbooks so we could have foreman-installer based on chef.

**Comment by PierreRambaud** [comment]
Hi,

It already installs Foreman chef (https://github.com/redguide/foreman/blob/master/attributes/default.rb#L15) and Smart proxy Chef (https://github.com/redguide/foreman/blob/master/attributes/foreman_proxy.rb#L18) but only for Ubuntu (at this time).

Regards

**Comment by ares** [comment]
Right, it installs the packages, but I can't see (might be lack of my chef knowledge) configuration of smart_proxy_chef. foreman_chef should work just fine.

**Comment by PierreRambaud** [comment]
it's right, there is no configuration about `smart_proxy_chef`, do all configuration parameters are in this file? (https://github.com/theforeman/smart_proxy_chef/blob/master/settings.d/chef.yml.example)

**Comment by ares** [comment]
Yes and I'll add all new options there (nothing planned soon)

Odesláno pomocí AquaMail pro Android
http://www.aqua-mail.com


Dne 29. června 2015 8:59:37 GoT <notifications@github.com> napsal:

**Comment by PierreRambaud** [comment]
If you want you can have a look here: https://github.com/redguide/foreman/pull/5
And tell me if it's what you need ;)

**Comment by PierreRambaud** [comment]
I think I can close this issue.
Regards
