### ISSUE TITLE
New 3.2.2 apache2 breaks cookbook

### ISSUE THREAD

**Issue by bcorner13** [redguide/foreman#7]
I fixed this https://github.com/svanzoest-cookbooks/apache2/pull/420/files
by updating the metadata file with
depends 'apache2' , '<=3.2.1'

I'm working on a branch to add centos/RHEL support.  Initially I'm working on 6.7 then will do 7.2.

**Comment by shortdudey123** [comment]
This can probably be closed since it looks like that code block being referenced in the PR is depreacted
https://github.com/sous-chefs/apache2/commit/4fd928f0ed626c3d7a1f8ac5ef5c29da01b3db5e

**Comment by PierreRambaud** [comment]
Oh yeah, nice catch, forget this issue ><
